services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gestao-evento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao_evento
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: jvitordev96/gestao-evento-backend
    container_name: gestao-evento-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/gestao_evento
      DB_USERNAME: root
      DB_PASSWORD: root

volumes:
  mysql_data:
